# Generated by Django 4.2.3 on 2023-07-21 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('issue_date', models.DateField()),
                ('checksum', models.CharField(max_length=64)),
            ],
        ),
    ]
